---
- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Add redis config to `/etc/redis.conf` 
  template:
    src:  redis.conf.j2
    dest: /etc/redis.conf
    owner: root
    mode: 0644
  become: yes

- name: Add redis sentinel config to `/etc/redis-sentinel.conf`
  template:
    src:  sentinel.conf.j2
    dest: /etc/redis-sentinel.conf
    owner: root
    mode: 0644
  become: yes

- name: Enable Redis Service on Boot
  ansible.builtin.systemd:
    name: redis
    enabled: yes

- name: Start Redis Service
  ansible.builtin.systemd:
    name: redis
    state: started
