---

- name: Start RabbitMQ Server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started

- name: Restart RabbitMQ Server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted