---
- name: Install OpenJDK JRE 8
  yum:
    name: java-1.8.0-openjdk
    state: present
    update_cache: true

- name: Add Cassandra Repo
  yum_repository:
    name: cassandra
    description: Apache Cassandra Repository
    baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
    gpgkey: https://www.apache.org/dist/cassandra/KEYS
    gpgcheck: yes

- name: Install Apache Cassandra
  yum:
    name: cassandra
    state: present
    update_cache: true

- name: Create cassandra config `/etc/cassandra/conf/cassandra.yaml`
  template:
    src:  cassandra.yaml.j2
    dest: /etc/cassandra/conf/cassandra.yaml
    owner: root
    mode: 0644  
  become: yes
