---
- name: Add Mongo GPG keys
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: Add MongoDB Repo
  ansible.builtin.apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
    state: present
    
- name: Install MongoDB & Additional Tools ( Python3 & PyMongo )
  apt:
    name: 
      - gnupg
      - mongodb-org 
      - python3
      - python3-pip
    state: present
    update_cache: true
