---

- name: Add new rabbit user
  command: rabbitmqctl add_user {{ rabbit_admin_user }} {{ rabbit_admin_password }}
  become: yes

- name: Set user to admin role
  command: rabbitmqctl set_user_tags {{ rabbit_admin_user }} administrator
  become: yes

- name: Grand user to all privilege
  command: rabbitmqctl set_permissions -p / {{ rabbit_admin_user }} ".*" ".*" ".*"
  become: yes

- name: Remove guest user
  command: rabbitmqctl delete_user guest
  become: yes

