---
- name: Enable EPEL ( Extra Package )
  yum:
    name: epel-release
    state: present
    update_cache: true

- name: Install Erlang & RabbitMQ
  yum:
    name: 
      - erlang
      - rabbitmq-server
    state: present
    update_cache: true
