---
- name: Create  database
  community.mysql.mysql_db:
    name: "{{ database_app1 }}"
    state: present
    login_host: 'localhost'
    login_user: 'root'
    login_password: "{{ mysql_root_password }}"