---
- name: Get MySQL RPM
  get_url:
    url: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    dest: /tmp/mysql57-community-release-el7-9.noarch.rpm
    checksum: md5:1a29601dc380ef2c7bc25e2a0e25d31e

- name: Install MySQL Package
  yum:
    name: /tmp/mysql57-community-release-el7-9.noarch.rpm
    state: present

- name: Install MySQL Server
  yum:
    name: 
      - mysql-server
      - MySQL-python
    state: present
    update_cache: true

- name: Enable MySQL Service on Boot
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes

- name: Start MySQL Server
  ansible.builtin.systemd:
    name: mysqld
    state: started

- name: Get Root tmp Password
  shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}' | tail -n 1
  register: mysql_temp_pass

- name: Set MySQL Root Password from tmp Password
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -uroot -p"{{ mysql_temp_pass.stdout }}"'

- name: Create `/root/.my.cnf` with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes