---
- name: Install OpenJDK JRE 8
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: true

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
